@Restaurants_HostAddress = https://localhost:7142




GET {{Restaurants_HostAddress}}/api/restaurants

###



@id=1
GET {{Restaurants_HostAddress}}/api/restaurants/{{id}}

###



POST {{Restaurants_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Tests",
  "Description": "Cozy restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tests.com",
  "ContactNumber": "555-1234",
  "City":"New york",
  "Street":"786 Main Avenue",
  "PostalCode" : "10-101"
}

###


GET https://localhost:7142/api/restaurants/4