@Restaurants.API_HostAddress = https://localhost:7142
@token = CfDJ8MkoIiO835ZDuygHXVhjuGSdbbcbFX41Nw_TMh_qV5Wq-WSyzlh9unrQRxqg5lM-R_Yi7yTBPtrgeDAtGEw2KwXUMX4-X0UOK-ptPnf_TX_mSQoyQJKk7Wn8m18dLQtiPRgWnRGR8eYyJPfZHBWLuR1MKmHkLxV1yRxfng-W7DVACwUtWNdkD1lYAcodwTCbsJr3ix-RODw3gywyLPpu6_gRaXbttkHodNCeR6kknedWUPjkU-A_pH5kZhWiQcHAPF1SKG7VMrRYb5awA_3T0yKXP2cpyrfMWK-mFGFmaOAYqMq_Uh-sZUH9YzKFrkCD-g9Y4fXxJTHDFCL3RZxdz4hP-GdRoF6E4pDxYOsPwj2OH2ls14lNo8snamHwkuYSuRtX_EBq5IGGdLQq_KiQi4tnktB-nsRpwbtm4aZy4AIRNACacSdQXio6g5SLx4vD4nVqDhz51wIVs6BB8d8QqVZIo7JLNTFHe40s21s1G0Bkv6xneK8OKoNgvJgI5CT4g-7XBK_3IdxFAGdGFPw0XfjHxRkr-TEN2eON6_9Ra0nLmWmOJydxuMYd1x1pwXTWA2pY2Jqjkvfs6kYd508Y9TkApCz1Hsilem63-QCq3pqDjFi_ll0H3PRBWvAGurESFEUxbE6m4Cv1CzPvX8BtGsdbBkNKdOl7ZzEOcEQ_UeJbb3-djDbfhkcWheUYXtLhwVHOAzW-SwQv_kWiCpPUfE9EIEE_hyo7gYvRygyy8YxYMjDY1Y_fCbM2KWnr3iKg7C8TKTb4UtZ62oMRls4gusISProxbyV5LEv_K8-w04p7JjV0UCqRez4Sjf73GxTauxd4_9B4MjyPetb6qkMWAFtONB4xlekDEnV6TXiJHxQHgxdnq7CXOOO8q7d7lDdpGQ

@restaurantId=0
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "owner restaurant",
  "description": "string",
  "category": "Indian",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "555-1234",
  "city": "string",
  "street": "string",
  "postalCode": "10-010"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email":"user@test.com",
  "password" : "Password1!"
}
###



POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email":"owner@test.com",
  "password" : "Password1!"
}
###





@id=5
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Authorization: Bearer {{token}}

###



GET {{Restaurants.API_HostAddress}}/api/restaurants?pageSize=-10&pageNumber=3
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "name": "updated restaurant",
  "description": "string",
  "category": "Indian",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "555-1234",
  "city": "string",
  "street": "string",
  "postalCode": "10-010"
}

###
