@Restaurants_HostAddress = https://localhost:7142




GET {{Restaurants_HostAddress}}/api/restaurants

###



@id=200
GET {{Restaurants_HostAddress}}/api/restaurants/{{id}}

###



POST {{Restaurants_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Test Tests",
  "Description": "Cozy restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tests.com",
  "ContactNumber": "555-1234",
  "City":"New york",
  "Street":"786 Main Avenue",
  "PostalCode" : "10-101"
}

###


@id=5
DELETE {{Restaurants_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
  "Name": "Sample Patch",
  "Description": "Sample restaurant",
  "HasDelivery": true
}

###
@id=145
GET {{Restaurants_HostAddress}}/api/restaurants/{{id}}

###
