@Restaurants_HostAddress = https://localhost:7142

GET {{Restaurants_HostAddress}}/api/weatherforecast 
Accept: application/json

###


GET {{Restaurants_HostAddress}}/api/restaurants

###



@id=1
GET {{Restaurants_HostAddress}}/api/restaurants/{{id}}

###

