@Restaurants.API_HostAddress = https://localhost:7142
@token = CfDJ8MkoIiO835ZDuygHXVhjuGRjTokPT2_LXthRPZqp1oC9yow4atr9UfzAU5KEdcURkyXHJhv5SbR7GnEUUTrTbB5ZaVfOMi1f3A_yERbMrVaAOgWsq-t5VaEH9DROacOcYVU6UR76Siwn7OHqOhn9-ypcL0mhE5VdWEtBLYhbEqt-0_Y2SH5tb9cx9w7q-lKjGewIF67f9L5JAiQtXwldlGbhWAzhxrfcMLoJODD8VUXP959klS2ziwwilLE3X4JkQ69edaLQoUOI4p3Sb5C9ubUZdsBqInSCeFPB8z53Ck5JBDLhgdTs2nMViuve9ejj2k7JOkmnDtFGtSIcf-ZTadae8b9Nltvs9APkr76bPR7z4UE0imAOt4DeM8lDivNT52jJvkm_QBpUW_-b8joxzwVkZqHghrYoSQUpmbbUUMT9WyJysWL1M9k0iUvLfd11ooAvNdBXyHdqjAZFITzWjYswofUaMzS3huXluO2xRxs23IbCOdpqGG55OnuadFvlqVobuR04ymmNOeOu1MYYpE2r6Gcy9YKXyslYwhq9v3lKzgKkhmw06f9FoN3iCnT40XtDzVMgZ5On6_uafmdxWjBrLgLYPNwXu2nlGTeDpvNEQWK2IcOQSk234JFvJLqw_r_gGJbkjnwWItbskBNqxx16zEjR4iMf0HlZJAPpjsAQR7N_Qh4t7Got4c0D2W6SvQ

@restaurantId=0
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "string",
  "description": "string",
  "category": "string",
  "hasDelivery": true,
  "contactEmail": "string",
  "contactNumber": "string",
  "city": "string",
  "street": "string",
  "postalCode": "string"
}

###





POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email":"user@test.com",
  "password" : "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email":"user@test.com",
  "password" : "Password1!"
}

