@Restaurants.API_HostAddress = https://localhost:7142
@token = CfDJ8MkoIiO835ZDuygHXVhjuGRBHk_R2NifumQa3Ek_jWD-eUEE9xTfmD7dXTJkXq-1Mqigj4TvMuldAWAPofWBGbIkdHz9jMPO8VUVgQsa6iIW5ymsl8tV8ghD6dcFpfOCJ_er6SPwJI6vHpUNt3FejkTA7uWcV6hsKH0focmGmpsJcj0KwNp03V_4ZUwdcJwrxd_ffZ6NWDv_W8p0CqGwvkxKZctNWRWgjX2UZzlq-RG1IW-aQ09hRoj5r5MTuFEDDAqwS2XrJQRooLqnCybymjSkY3GJmo-YB8uYhcsNyhuxUprgtSUAWjOGe5XyyEoYBTpbyRyNdNXwGEhhgiD4oCe69Q3dLOAQnsGPYJ2d6gC5PBHDLTesdFD1bK61tMYa9f4-AC-xEg9KYZXnjDQlMRhskz-X6iHQyQmAWYUe3h7iKyAgPvZPE1oFDmqSZCbASc6lOVC1-6KFSqIk7Z8ADL_L-nvzeFdPcEPOffxjFNxFo6R_QbOqaZoUd1F7HLbbY7kAeJh_oQpB3WsmWod2l1mC84ofXxcGvUaEdkR-ICYJUESadXCGh0uPo-zxfEl-_T1wx12r6uc5laX4YOf7b38hNwYcfvw4UMLVOHGzBj1jIj1mqrGlhv_2A4gPPVOpnA59GAIHpXYRygkgXexFFUcqpNxm79tm1V048GNJwG17BKIIxNRe2BvF3ddhv9tTGNxrAWYVuxXHarfBi1E0KwcIX8TehweSVtR30QUj3Z5k_RA0pDqCj01dlBL5k8eZGtf6mwFUfInvEx0Z8KV2B5s-J8Yp_Rqrg6aVYa-eus1vQZJMqAx-G3Vy3x4KlSvSqwbWVQjXZ0SUqU0ROCuIrl-QO80pSNHEW5nCb2_6b0IgaPkua2q9LQHojUzirSUj1A

@restaurantId=0
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "owner restaurant",
  "description": "string",
  "category": "Indian",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "555-1234",
  "city": "string",
  "street": "string",
  "postalCode": "10-010"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email":"user@test.com",
  "password" : "Password1!"
}
###



POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email":"owner@test.com",
  "password" : "Password1!"
}
###





@id=5
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
